[DOC] description on how to build a windows installer (#5267)
* fix NSIS EnvVarUpdate script when using nsis-3.06.1 giving

Error: unterminated string parsing line at macro:_IncludeStrFunction1:7

Error in macro _IncludeStrFunction1 on macroline 7

!include: error in script: "EnvVarUpdate.nsh" on line 49

* fix package error for NSIS when multiple redist exe's are found in the VS installation dir

* switch to https

* for minor formatting

* prelim installer instructions

* cleanup VS redist finding routine

* Win installer script fix

* fix submodules