switch to using a library-interface for SIMDe to avoid `...thirdparty\simde\simde\x86\sse.h(3363,39): error C4100: 'i': unreferenced formal parameter ` on MSVC due to external includes since we are using /we4100 and /we4189