clang: Add missing <thread> header
LLVM/clang version 21+ seems to be a bit more strict than the default
17 found on the GitHub runner.  Without the `<thread>` header it
reports the following error:

```
ExternalProcess.cpp:257:29: error: no member named 'sleep_for' in namespace 'std::this_thread'
```